name: igplrealestatercrm
description: "A Real Estate CRM Flutter application for lead management"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '^3.8.0'
  flutter: ">=3.24.0"

dependencies:
  flutter:
    sdk: flutter

  # URL Launcher (moved to correct position)
  url_launcher: ^6.2.2

  # Firebase
  firebase_core: ^2.24.2
  firebase_auth: ^4.15.3
  cloud_firestore: ^4.13.6

  # State Management
  flutter_riverpod: ^2.4.9

  # Storage & Utilities
  shared_preferences: ^2.2.2
  intl: ^0.19.0

  # Notifications
  flutter_local_notifications: ^17.2.3
  timezone: ^0.9.4

  # UI Components
  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  # Add app icons and assets here if needed
  # assets:
  #   - images/

  # Add custom fonts here if needed
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf